# Python CircleCI 2.0 configuration file
version: 2
jobs:
  # running commands on a basic image
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: Saying Hello
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'

